### ISSUE TITLE
Running on DBP100K

### ISSUE THREAD

**Issue by DexterZeng** [h324yang/HMAN#4]
Hi, thank you very much for providing the code, which has been really useful.

When running run.py on DBP100K, a ResourceExhaustedError happened. I wonder which kind of GPUs did you use? Mine is two Titan Xs which seem to be not enough. 

Thank you for your time and I look forward to your reply.

**Comment by h324yang** [comment]
@zoezou2015 any suggestions?

**Comment by zoezou2015** [comment]
Hi, thanks for your interest in our work. We also encountered the same resource error as you when running on DBP100K. We tried to use smaller dimensions that result in smaller model size but also strong performance.

**Comment by DexterZeng** [comment]
Hi, thank you for the tip. I have reduced the dimensions by half according to the paper and it indeed worked. 

Thank you again for your help.
